### ISSUE TITLE
Not able to use riscv-vp with the vp-breadboard

### ISSUE THREAD

**Issue by laurversanu** [agra-uni-bremen/virtual-breadboard#10]
The main issue is that i cannot start the connection between these two, and i would be very thankful if you could help me with a guide.

And another issue is that the "vp-breadboard -h" command doesn't work, hope that you can help with this too.

Thanks!

**Comment by Cirromulus** [comment]
>The main issue is that i cannot start the connection between these two

Note that the RISCV-VP is a set of individual confiurations (i.e. processors).
I think only the `hifive-vp` configuration opens up a gpio-server.
Some example programs for that can be found in this repo: https://github.com/agra-uni-bremen/sifive-hifive1
If you want to run the example *snake* program, you would follow the Readme there.

To recap:

- virtual-breadboard simulates **off-chip devices**
- riscv-vp simulates **SoCs**
- sifive-hifive contains software **programs** for hifive-1 boards, which can be simulated by the hifive-vp that interacts with the virtual-breadboard for an interactive environment GUI.


If you just want to test whether it connects to anything (Or build your own on-chip simulation, e.g. connect it to AVR sim!), you can try out the protocol test server int this repo without separate programs (`virtual-breadboard-gui/build$ ./lib/protocol/vbb-cli-server 1400`)

>And another issue is that the "vp-breadboard -h" command doesn't work

What does not work? What is your output? Please specify.

**Comment by laurversanu** [comment]
Thanks a lot!

În dum., 4 iun. 2023 la 18:45 Pascal ***@***.***> a scris:
